export const BOOKS_FETCH_START = "BOOKS_FETCH_START";
export const BOOKS_FETCH_IN_PROGRESS = "BOOKS_FETCH_IN_PROGRESS";
export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";
export const BOOKS_FETCH_ERROR = "BOOKS_FETCH_ERROR";
